export const deployControlLogicalTables = [
  "runnerProfiles",
  "spaces",
  "sources",
  "sourceSnapshots",
  "connections",
  "secretBlobs",
  "operatorConnectionDefaults",
  "installConfigs",
  "installations",
  "capsuleCompatibilityReports",
  "deploymentProfiles",
  "installationDependencies",
  "dependencySnapshots",
  "outputSnapshots",
  "outputShares",
  "runGroups",
  "runs",
  "runsInputs",
  "stateSnapshots",
  "deployments",
  "billingAccounts",
  "spaceSubscriptions",
  "creditBalances",
  "usageEvents",
  "creditReservations",
  "credentialMintEvents",
  "securityFindings",
  "auditEvents",
  "backups",
] as const;

export type DeployControlLogicalTable =
  typeof deployControlLogicalTables[number];

export const deployControlD1TableNames = {
  runnerProfiles: "runner_profiles",
  spaces: "spaces",
  sources: "sources",
  sourceSnapshots: "source_snapshots",
  connections: "connections",
  secretBlobs: "secret_blobs",
  operatorConnectionDefaults: "operator_connection_defaults",
  installConfigs: "install_configs",
  installations: "installations",
  capsuleCompatibilityReports: "capsule_compatibility_reports",
  deploymentProfiles: "deployment_profiles",
  installationDependencies: "installation_dependencies",
  dependencySnapshots: "dependency_snapshots",
  outputSnapshots: "output_snapshots",
  outputShares: "output_shares",
  runGroups: "run_groups",
  runs: "runs",
  runsInputs: "runs_inputs",
  stateSnapshots: "state_snapshots",
  deployments: "deployments",
  billingAccounts: "billing_accounts",
  spaceSubscriptions: "space_subscriptions",
  creditBalances: "credit_balances",
  usageEvents: "usage_events",
  creditReservations: "credit_reservations",
  credentialMintEvents: "credential_mint_events",
  securityFindings: "security_findings",
  auditEvents: "audit_events",
  backups: "backups",
} as const satisfies Record<DeployControlLogicalTable, string>;

export const deployControlPostgresTableNames = {
  runnerProfiles: "takosumi_runner_profiles",
  spaces: "takosumi_spaces",
  sources: "takosumi_sources",
  sourceSnapshots: "takosumi_source_snapshots",
  connections: "takosumi_connections",
  secretBlobs: "takosumi_connection_secret_blobs",
  operatorConnectionDefaults: "takosumi_operator_connection_defaults",
  installConfigs: "takosumi_install_configs",
  installations: "takosumi_opentofu_installations",
  capsuleCompatibilityReports: "takosumi_capsule_compatibility_reports",
  deploymentProfiles: "takosumi_deployment_profiles",
  installationDependencies: "takosumi_installation_dependencies",
  dependencySnapshots: "takosumi_dependency_snapshots",
  outputSnapshots: "takosumi_output_snapshots",
  outputShares: "takosumi_output_shares",
  runGroups: "takosumi_run_groups",
  runs: "takosumi_runs",
  runsInputs: "takosumi_plan_run_inputs",
  stateSnapshots: "takosumi_state_snapshots",
  deployments: "takosumi_opentofu_deployments",
  billingAccounts: "takosumi_billing_accounts",
  spaceSubscriptions: "takosumi_space_subscriptions",
  creditBalances: "takosumi_credit_balances",
  usageEvents: "takosumi_usage_events",
  creditReservations: "takosumi_credit_reservations",
  credentialMintEvents: "takosumi_credential_mint_events",
  securityFindings: "takosumi_security_findings",
  auditEvents: "takosumi_audit_events",
  backups: "takosumi_backups",
} as const satisfies Record<DeployControlLogicalTable, string>;
