// Generated by scripts/build-credential-recipe-assets.ts. Do not edit.
import type { CredentialRecipe } from "./credential-recipes.ts";

export const BUILT_IN_CREDENTIAL_RECIPES: readonly CredentialRecipe[] = [
  {
    "id": "aws",
    "displayName": "AWS",
    "providerRule": "aws",
    "terraformSource": [
      "hashicorp/aws",
      "registry.opentofu.org/hashicorp/aws"
    ],
    "envNames": [
      "AWS_ACCESS_KEY_ID",
      "AWS_SECRET_ACCESS_KEY",
      "AWS_SESSION_TOKEN",
      "AWS_WEB_IDENTITY_TOKEN_FILE",
      "AWS_ROLE_ARN",
      "AWS_REGION",
      "AWS_DEFAULT_REGION",
      "AWS_ENDPOINT_URL_S3"
    ],
    "requiredEnvGroups": [
      [
        "AWS_ACCESS_KEY_ID",
        "AWS_SECRET_ACCESS_KEY"
      ],
      [
        "AWS_WEB_IDENTITY_TOKEN_FILE",
        "AWS_ROLE_ARN"
      ]
    ],
    "authModes": {
      "static_keys": {
        "env": {
          "AWS_ACCESS_KEY_ID": {
            "from": "secret",
            "name": "access_key_id"
          },
          "AWS_SECRET_ACCESS_KEY": {
            "from": "secret",
            "name": "secret_access_key"
          },
          "AWS_SESSION_TOKEN": {
            "from": "secret",
            "name": "session_token"
          },
          "AWS_REGION": {
            "from": "value",
            "name": "region"
          },
          "AWS_DEFAULT_REGION": {
            "from": "value",
            "name": "region"
          }
        }
      },
      "assume_role": {
        "env": {
          "AWS_ACCESS_KEY_ID": {
            "from": "generated",
            "name": "access_key_id"
          },
          "AWS_SECRET_ACCESS_KEY": {
            "from": "generated",
            "name": "secret_access_key"
          },
          "AWS_SESSION_TOKEN": {
            "from": "generated",
            "name": "session_token"
          },
          "AWS_REGION": {
            "from": "value",
            "name": "region"
          },
          "AWS_DEFAULT_REGION": {
            "from": "value",
            "name": "region"
          }
        },
        "preRun": {
          "type": "aws_sts_assume_role",
          "inputs": {
            "role_arn": {
              "from": "value",
              "name": "role_arn"
            }
          }
        }
      },
      "web_identity": {
        "env": {
          "AWS_WEB_IDENTITY_TOKEN_FILE": {
            "from": "value",
            "name": "token_file"
          },
          "AWS_ROLE_ARN": {
            "from": "value",
            "name": "role_arn"
          },
          "AWS_REGION": {
            "from": "value",
            "name": "region"
          }
        }
      }
    }
  },
  {
    "id": "azurerm",
    "displayName": "Azure Resource Manager",
    "providerRule": "azurerm",
    "terraformSource": [
      "hashicorp/azurerm",
      "registry.opentofu.org/hashicorp/azurerm"
    ],
    "envNames": [
      "ARM_CLIENT_ID",
      "ARM_CLIENT_SECRET",
      "ARM_TENANT_ID",
      "ARM_SUBSCRIPTION_ID",
      "AZURE_CLIENT_ID",
      "AZURE_CLIENT_SECRET",
      "AZURE_TENANT_ID",
      "AZURE_SUBSCRIPTION_ID"
    ],
    "requiredEnvGroups": [
      [
        "ARM_CLIENT_ID",
        "ARM_CLIENT_SECRET",
        "ARM_TENANT_ID",
        "ARM_SUBSCRIPTION_ID"
      ],
      [
        "AZURE_CLIENT_ID",
        "AZURE_CLIENT_SECRET",
        "AZURE_TENANT_ID",
        "AZURE_SUBSCRIPTION_ID"
      ]
    ],
    "authModes": {
      "arm_client_secret": {
        "env": {
          "ARM_CLIENT_ID": {
            "from": "value",
            "name": "client_id"
          },
          "ARM_CLIENT_SECRET": {
            "from": "secret",
            "name": "client_secret"
          },
          "ARM_TENANT_ID": {
            "from": "value",
            "name": "tenant_id"
          },
          "ARM_SUBSCRIPTION_ID": {
            "from": "value",
            "name": "subscription_id"
          }
        }
      },
      "azure_client_secret": {
        "env": {
          "AZURE_CLIENT_ID": {
            "from": "value",
            "name": "client_id"
          },
          "AZURE_CLIENT_SECRET": {
            "from": "secret",
            "name": "client_secret"
          },
          "AZURE_TENANT_ID": {
            "from": "value",
            "name": "tenant_id"
          },
          "AZURE_SUBSCRIPTION_ID": {
            "from": "value",
            "name": "subscription_id"
          }
        }
      }
    }
  },
  {
    "id": "cloudflare",
    "displayName": "Cloudflare",
    "providerRule": "cloudflare",
    "terraformSource": [
      "cloudflare/cloudflare",
      "registry.opentofu.org/cloudflare/cloudflare"
    ],
    "envNames": [
      "CLOUDFLARE_API_TOKEN",
      "CLOUDFLARE_API_KEY",
      "CLOUDFLARE_EMAIL",
      "CLOUDFLARE_ACCOUNT_ID",
      "CLOUDFLARE_ZONE_ID",
      "CF_API_TOKEN"
    ],
    "requiredEnvGroups": [
      [
        "CLOUDFLARE_API_TOKEN"
      ],
      [
        "CF_API_TOKEN"
      ],
      [
        "CLOUDFLARE_API_KEY",
        "CLOUDFLARE_EMAIL"
      ]
    ],
    "authModes": {
      "api_token": {
        "env": {
          "CLOUDFLARE_API_TOKEN": {
            "from": "secret",
            "name": "api_token"
          },
          "CLOUDFLARE_ACCOUNT_ID": {
            "from": "value",
            "name": "account_id"
          },
          "CLOUDFLARE_ZONE_ID": {
            "from": "value",
            "name": "zone_id"
          }
        }
      },
      "cf_api_token": {
        "env": {
          "CF_API_TOKEN": {
            "from": "secret",
            "name": "api_token"
          }
        }
      },
      "global_key": {
        "env": {
          "CLOUDFLARE_API_KEY": {
            "from": "secret",
            "name": "api_key"
          },
          "CLOUDFLARE_EMAIL": {
            "from": "value",
            "name": "email"
          }
        }
      }
    }
  },
  {
    "id": "digitalocean",
    "displayName": "DigitalOcean",
    "providerRule": "digitalocean",
    "terraformSource": [
      "digitalocean/digitalocean",
      "registry.opentofu.org/digitalocean/digitalocean"
    ],
    "envNames": [
      "DIGITALOCEAN_TOKEN",
      "SPACES_ACCESS_KEY_ID",
      "SPACES_SECRET_ACCESS_KEY"
    ],
    "requiredEnvGroups": [
      [
        "DIGITALOCEAN_TOKEN"
      ]
    ],
    "authModes": {
      "token": {
        "env": {
          "DIGITALOCEAN_TOKEN": {
            "from": "secret",
            "name": "token"
          }
        }
      },
      "spaces": {
        "env": {
          "DIGITALOCEAN_TOKEN": {
            "from": "secret",
            "name": "token"
          },
          "SPACES_ACCESS_KEY_ID": {
            "from": "secret",
            "name": "spaces_access_key_id"
          },
          "SPACES_SECRET_ACCESS_KEY": {
            "from": "secret",
            "name": "spaces_secret_access_key"
          }
        }
      }
    }
  },
  {
    "id": "generic-env",
    "displayName": "Generic environment variables",
    "terraformSource": "*",
    "declaredEnv": true,
    "authModes": {
      "env": {
        "env": {
          "*": {
            "from": "user_defined"
          }
        },
        "files": {
          "*": {
            "from": "user_defined"
          }
        }
      }
    }
  },
  {
    "id": "github",
    "displayName": "GitHub",
    "providerRule": "github",
    "terraformSource": [
      "integrations/github",
      "github/github",
      "registry.opentofu.org/integrations/github",
      "registry.opentofu.org/github/github"
    ],
    "envNames": [
      "GITHUB_TOKEN"
    ],
    "requiredEnvGroups": [
      [
        "GITHUB_TOKEN"
      ]
    ],
    "authModes": {
      "token": {
        "env": {
          "GITHUB_TOKEN": {
            "from": "secret",
            "name": "token"
          }
        }
      }
    }
  },
  {
    "id": "google",
    "displayName": "Google Cloud",
    "providerRule": "google",
    "terraformSource": [
      "hashicorp/google",
      "hashicorp/google-beta",
      "registry.opentofu.org/hashicorp/google",
      "registry.opentofu.org/hashicorp/google-beta"
    ],
    "envNames": [
      "GOOGLE_CREDENTIALS",
      "GOOGLE_APPLICATION_CREDENTIALS",
      "GOOGLE_CLOUD_PROJECT",
      "GOOGLE_PROJECT",
      "GOOGLE_REGION"
    ],
    "requiredEnvGroups": [
      [
        "GOOGLE_CREDENTIALS"
      ],
      [
        "GOOGLE_APPLICATION_CREDENTIALS"
      ]
    ],
    "authModes": {
      "service_account_json": {
        "env": {
          "GOOGLE_CREDENTIALS": {
            "from": "secret",
            "name": "service_account_json"
          },
          "GOOGLE_CLOUD_PROJECT": {
            "from": "value",
            "name": "project_id"
          },
          "GOOGLE_PROJECT": {
            "from": "value",
            "name": "project_id"
          },
          "GOOGLE_REGION": {
            "from": "value",
            "name": "region"
          }
        }
      },
      "service_account_file": {
        "env": {
          "GOOGLE_APPLICATION_CREDENTIALS": {
            "from": "literal",
            "value": "/run/takosumi/google-credentials.json"
          },
          "GOOGLE_PROJECT": {
            "from": "value",
            "name": "project_id"
          }
        },
        "files": {
          "google-credentials.json": {
            "from": "secret",
            "name": "service_account_json",
            "envName": "GOOGLE_APPLICATION_CREDENTIALS",
            "mode": 384
          }
        }
      },
      "impersonation": {
        "env": {
          "GOOGLE_CREDENTIALS": {
            "from": "generated",
            "name": "access_token_json"
          },
          "GOOGLE_CLOUD_PROJECT": {
            "from": "value",
            "name": "project_id"
          }
        },
        "preRun": {
          "type": "gcp_service_account_impersonation",
          "inputs": {
            "service_account_email": {
              "from": "value",
              "name": "service_account_email"
            }
          }
        }
      }
    }
  },
  {
    "id": "hcloud",
    "displayName": "Hetzner Cloud",
    "providerRule": "hcloud",
    "terraformSource": [
      "hetznercloud/hcloud",
      "registry.opentofu.org/hetznercloud/hcloud"
    ],
    "envNames": [
      "HCLOUD_TOKEN"
    ],
    "requiredEnvGroups": [
      [
        "HCLOUD_TOKEN"
      ]
    ],
    "authModes": {
      "token": {
        "env": {
          "HCLOUD_TOKEN": {
            "from": "secret",
            "name": "token"
          }
        }
      }
    }
  },
  {
    "id": "helm",
    "displayName": "Helm",
    "providerRule": "helm",
    "terraformSource": [
      "hashicorp/helm",
      "registry.opentofu.org/hashicorp/helm"
    ],
    "envNames": [
      "KUBE_CONFIG_PATH",
      "KUBE_HOST",
      "KUBE_TOKEN",
      "KUBE_CLUSTER_CA_CERT_DATA"
    ],
    "requiredEnvGroups": [
      [
        "KUBE_CONFIG_PATH"
      ],
      [
        "KUBE_HOST",
        "KUBE_TOKEN"
      ]
    ],
    "authModes": {
      "kubeconfig": {
        "env": {
          "KUBE_CONFIG_PATH": {
            "from": "value",
            "name": "kubeconfig_path"
          }
        }
      },
      "token": {
        "env": {
          "KUBE_HOST": {
            "from": "value",
            "name": "host"
          },
          "KUBE_TOKEN": {
            "from": "secret",
            "name": "token"
          },
          "KUBE_CLUSTER_CA_CERT_DATA": {
            "from": "secret",
            "name": "cluster_ca_cert_data"
          }
        }
      }
    }
  },
  {
    "id": "kubernetes",
    "displayName": "Kubernetes",
    "providerRule": "kubernetes",
    "terraformSource": [
      "hashicorp/kubernetes",
      "registry.opentofu.org/hashicorp/kubernetes"
    ],
    "envNames": [
      "KUBE_CONFIG_PATH",
      "KUBE_HOST",
      "KUBE_TOKEN",
      "KUBE_CLUSTER_CA_CERT_DATA"
    ],
    "requiredEnvGroups": [
      [
        "KUBE_CONFIG_PATH"
      ],
      [
        "KUBE_HOST",
        "KUBE_TOKEN"
      ]
    ],
    "authModes": {
      "kubeconfig": {
        "env": {
          "KUBE_CONFIG_PATH": {
            "from": "value",
            "name": "kubeconfig_path"
          }
        }
      },
      "token": {
        "env": {
          "KUBE_HOST": {
            "from": "value",
            "name": "host"
          },
          "KUBE_TOKEN": {
            "from": "secret",
            "name": "token"
          },
          "KUBE_CLUSTER_CA_CERT_DATA": {
            "from": "secret",
            "name": "cluster_ca_cert_data"
          }
        }
      }
    }
  },
  {
    "id": "openstack",
    "displayName": "OpenStack",
    "providerRule": "openstack",
    "terraformSource": [
      "terraform-provider-openstack/openstack",
      "registry.opentofu.org/terraform-provider-openstack/openstack"
    ],
    "envNames": [
      "OS_CLOUD",
      "OS_AUTH_URL",
      "OS_USERNAME",
      "OS_PASSWORD",
      "OS_PROJECT_NAME",
      "OS_USER_DOMAIN_NAME",
      "OS_PROJECT_DOMAIN_NAME",
      "OS_REGION_NAME",
      "OS_APPLICATION_CREDENTIAL_ID",
      "OS_APPLICATION_CREDENTIAL_SECRET"
    ],
    "requiredEnvGroups": [
      [
        "OS_CLOUD"
      ],
      [
        "OS_AUTH_URL",
        "OS_USERNAME",
        "OS_PASSWORD",
        "OS_PROJECT_NAME"
      ],
      [
        "OS_AUTH_URL",
        "OS_APPLICATION_CREDENTIAL_ID",
        "OS_APPLICATION_CREDENTIAL_SECRET"
      ]
    ],
    "authModes": {
      "cloud_profile": {
        "env": {
          "OS_CLOUD": {
            "from": "value",
            "name": "cloud"
          }
        }
      },
      "password": {
        "env": {
          "OS_AUTH_URL": {
            "from": "value",
            "name": "auth_url"
          },
          "OS_USERNAME": {
            "from": "value",
            "name": "username"
          },
          "OS_PASSWORD": {
            "from": "secret",
            "name": "password"
          },
          "OS_PROJECT_NAME": {
            "from": "value",
            "name": "project_name"
          },
          "OS_USER_DOMAIN_NAME": {
            "from": "value",
            "name": "user_domain_name"
          },
          "OS_PROJECT_DOMAIN_NAME": {
            "from": "value",
            "name": "project_domain_name"
          },
          "OS_REGION_NAME": {
            "from": "value",
            "name": "region"
          }
        }
      },
      "application_credential": {
        "env": {
          "OS_AUTH_URL": {
            "from": "value",
            "name": "auth_url"
          },
          "OS_APPLICATION_CREDENTIAL_ID": {
            "from": "secret",
            "name": "application_credential_id"
          },
          "OS_APPLICATION_CREDENTIAL_SECRET": {
            "from": "secret",
            "name": "application_credential_secret"
          },
          "OS_REGION_NAME": {
            "from": "value",
            "name": "region"
          }
        }
      }
    }
  },
  {
    "id": "s3-compatible",
    "displayName": "S3-compatible object storage",
    "providerRule": "aws",
    "terraformSource": [
      "hashicorp/aws",
      "registry.opentofu.org/hashicorp/aws"
    ],
    "envNames": [
      "AWS_ACCESS_KEY_ID",
      "AWS_SECRET_ACCESS_KEY",
      "AWS_REGION",
      "AWS_DEFAULT_REGION",
      "AWS_ENDPOINT_URL_S3"
    ],
    "requiredEnvGroups": [
      [
        "AWS_ACCESS_KEY_ID",
        "AWS_SECRET_ACCESS_KEY"
      ]
    ],
    "authModes": {
      "static_keys_with_endpoint": {
        "env": {
          "AWS_ACCESS_KEY_ID": {
            "from": "secret",
            "name": "access_key_id"
          },
          "AWS_SECRET_ACCESS_KEY": {
            "from": "secret",
            "name": "secret_access_key"
          },
          "AWS_REGION": {
            "from": "value",
            "name": "region"
          },
          "AWS_DEFAULT_REGION": {
            "from": "value",
            "name": "region"
          },
          "AWS_ENDPOINT_URL_S3": {
            "from": "value",
            "name": "endpoint"
          }
        }
      }
    }
  },
  {
    "id": "scaleway",
    "displayName": "Scaleway",
    "providerRule": "scaleway",
    "terraformSource": [
      "scaleway/scaleway",
      "registry.opentofu.org/scaleway/scaleway"
    ],
    "envNames": [
      "SCW_ACCESS_KEY",
      "SCW_SECRET_KEY",
      "SCW_DEFAULT_PROJECT_ID",
      "SCW_DEFAULT_ORGANIZATION_ID",
      "SCW_DEFAULT_REGION",
      "SCW_DEFAULT_ZONE",
      "SCW_PROFILE"
    ],
    "requiredEnvGroups": [
      [
        "SCW_ACCESS_KEY",
        "SCW_SECRET_KEY"
      ],
      [
        "SCW_PROFILE"
      ]
    ],
    "authModes": {
      "access_key": {
        "env": {
          "SCW_ACCESS_KEY": {
            "from": "secret",
            "name": "access_key"
          },
          "SCW_SECRET_KEY": {
            "from": "secret",
            "name": "secret_key"
          },
          "SCW_DEFAULT_PROJECT_ID": {
            "from": "value",
            "name": "project_id"
          },
          "SCW_DEFAULT_ORGANIZATION_ID": {
            "from": "value",
            "name": "organization_id"
          },
          "SCW_DEFAULT_REGION": {
            "from": "value",
            "name": "region"
          },
          "SCW_DEFAULT_ZONE": {
            "from": "value",
            "name": "zone"
          }
        }
      },
      "profile": {
        "env": {
          "SCW_PROFILE": {
            "from": "value",
            "name": "profile"
          }
        }
      }
    }
  },
  {
    "id": "vercel",
    "displayName": "Vercel",
    "providerRule": "vercel",
    "terraformSource": [
      "vercel/vercel",
      "registry.opentofu.org/vercel/vercel"
    ],
    "envNames": [
      "VERCEL_API_TOKEN"
    ],
    "requiredEnvGroups": [
      [
        "VERCEL_API_TOKEN"
      ]
    ],
    "authModes": {
      "api_token": {
        "env": {
          "VERCEL_API_TOKEN": {
            "from": "secret",
            "name": "api_token"
          }
        }
      }
    }
  },
  {
    "id": "vultr",
    "displayName": "Vultr",
    "providerRule": "vultr",
    "terraformSource": [
      "vultr/vultr",
      "registry.opentofu.org/vultr/vultr"
    ],
    "envNames": [
      "VULTR_API_KEY"
    ],
    "requiredEnvGroups": [
      [
        "VULTR_API_KEY"
      ]
    ],
    "authModes": {
      "api_key": {
        "env": {
          "VULTR_API_KEY": {
            "from": "secret",
            "name": "api_key"
          }
        }
      }
    }
  }
];
