export type {
  FetchLike,
  HostCapabilities,
  HostDiscovery,
  MobileConnectPayload,
  MobileHostCenterSource,
  MobileKeyValueStore,
  MobileKnownHost,
  MobileCallIntent,
  MobileClipboardText,
  MobileBiometricPrompt,
  MobileSessionUnlockMode,
  MobileSessionUnlockOptions,
  MobileLocalNotification,
  MobileHostableProductKind,
  MobilePushNotification,
  MobilePushNotificationEventKind,
  MobilePushProvider,
  MobilePushRegistration,
  MobilePushRegistrationInput,
  MobileRoutePayload,
  MobileAuthRequest,
  MobileProductAdapter,
  MobileProductKind,
  MobileSecureStore,
  MobileSession,
  NativeBridge,
  NativeBridgeCapabilities,
  OidcAuthorizationUrlInput,
  OidcCallbackResult,
  OidcMetadata,
  OidcTokenExchangeInput,
  OidcTokenResponse,
  PkcePair,
  ProductWellKnown,
  ProductWellKnownEndpoints,
  TakosumiWellKnown,
} from "./types.ts";

export { discoverHost } from "./discovery.ts";
export {
  createMobileApiClient,
  MobileApiError,
  NOTIFICATION_PUSHER_REGISTRATION_PATH,
  registerNotificationPusherWithHost,
  resolveNotificationPusherEndpoint,
  unregisterNotificationPusherWithHost,
  type MobileApiClient,
  type MobileHostNotificationPusherRegistrationInput,
  type MobileHostNotificationPusherUnregistrationInput,
} from "./api.ts";
export {
  normalizeNotificationPusherGatewayUrl,
  type NotificationPusher,
} from "../../contract/notification-pushers.ts";
export {
  createMobileClientController,
  type CreateMobileClientControllerOptions,
  type MobileClientActionResult,
  type MobileClientController,
  type MobileClientCopy,
  type MobilePushNotificationCallbackInput,
  type MobilePushRegistrationCallbackInput,
  type MobileClientState,
} from "./client.ts";
export {
  parseMobileConnectInput,
  parseMobileProductKind,
  parseMobileRouteInput,
} from "./handoff.ts";
export {
  clearMobileKnownHosts,
  loadMobileKnownHosts,
  mobileKnownHostsStorageKey,
  rememberMobileKnownHost,
  removeMobileKnownHost,
  type MobileKnownHostsStorageInput,
  type RemoveMobileKnownHostInput,
  type RememberMobileKnownHostInput,
} from "./known-hosts.ts";
export {
  createOidcAuthorizationUrl,
  createPkcePair,
  createRandomState,
  exchangeOidcCode,
  fetchOidcMetadata,
  parseOidcCallback,
} from "./oidc.ts";
export {
  beginMobileOidcSignIn,
  clearMobileSession,
  completeMobileOidcSignIn,
  ensureFreshMobileSession,
  isOidcCallbackPayload,
  loadMobileSession,
  mobileAuthRequestStorageKey,
  mobileSessionStorageKey,
  persistMobileSession,
  refreshMobileSession,
  type BeginMobileOidcSignInInput,
  type BeginMobileOidcSignInResult,
  type CompleteMobileOidcSignInInput,
  type EnsureFreshMobileSessionInput,
  type PersistMobileSessionInput,
  type RefreshMobileSessionInput,
} from "./auth.ts";
export {
  createMobileConnectUrl,
  createMobileHostRouteUrl,
  openMobileHostRoute,
  createTakosumiHostCenterUrl,
  hostEndpoint,
  normalizeHostUrl,
} from "./url.ts";
export {
  appendUniqueMobileItemsByKey,
  appendUniqueMobileItemsById,
  formatMobilePreviewDate,
  prependUniqueMobileItemsByKey,
} from "./preview.ts";
export {
  canSubmitMobileText,
  isMobileTextPresent,
  mobileOptionalText,
  mobilePlainText,
  mobileTextRemaining,
  type CanSubmitMobileTextInput,
  type MobilePlainTextOptions,
} from "./text.ts";
export {
  mobileNumber,
  mobileRecord,
  type MobileNumberOptions,
} from "./data.ts";
export { isMobileAbortError, mobileErrorMessage } from "./error.ts";
export {
  confirmMobileAction,
  type ConfirmMobileActionInput,
} from "./confirm.ts";
export {
  shareMobileUrl,
  type MobileShareData,
  type MobileShareNavigator,
  type MobileShareUrlInput,
} from "./share.ts";
export { requireMobileProductKey } from "./product-key.ts";
export {
  copyMobileText,
  createFirstRunActions,
  createHostCenterHref,
  createMobileReturnUri,
  type CopyMobileTextInput,
  type FirstRunAction,
} from "./shell.ts";
export {
  createBrowserNativeBridge,
  type BrowserNativeBridgeOptions,
  type BrowserLocalStorage,
  type BrowserNativeWindow,
} from "./native.ts";
export {
  createTauriMobilePushPluginAdapter,
  createTauriOpenerCallIntentAdapter,
  authenticateBiometric,
  createTauriInvokeKeystoreAdapter,
  createTauriKeystoreStrongholdPassword,
  createTauriMobileDefaultProductBridge,
  createTauriMobileProductBridge,
  createTauriMobileProductStorageNames,
  createTauriPersistentStrongholdPassword,
  createTauriPluginNativeBridge,
  createTauriPushNotificationsAdapter,
  createTauriStrongholdSecureStore,
  detectTauriRuntime,
  isTauriMobilePlatform,
  type CreateTauriInvokeKeystoreAdapterOptions,
  type CreateTauriKeystoreStrongholdPasswordOptions,
  type CreateTauriMobileDefaultProductBridgeOptions,
  type CreateTauriMobileProductStorageNamesOptions,
  type CreateTauriPersistentStrongholdPasswordOptions,
  type CreateTauriMobilePushPluginAdapterOptions,
  type CreateTauriOpenerCallIntentAdapterOptions,
  type CreateTauriMobileProductBridgeOptions,
  type CreateTauriPluginNativeBridgeOptions,
  type CreateTauriPushNotificationsAdapterOptions,
  type CreateTauriStrongholdSecureStoreOptions,
  type TauriBiometricAdapter,
  type TauriBiometricAuthOptions,
  type TauriBarcodeScannerAdapter,
  type TauriBarcodeScannerModule,
  type TauriDeepLinkAdapter,
  type TauriInvokeAdapter,
  type TauriKeystoreAdapter,
  type TauriNotificationAdapter,
  type TauriOpenerAdapter,
  type TauriCallIntentAdapter,
  type TauriClipboardTextAdapter,
  type TauriMobilePushPermission,
  type TauriMobilePushNotification,
  type TauriMobilePushPluginModule,
  type TauriMobilePushTokenRefresh,
  type TauriPathAdapter,
  type TauriPlatform,
  type TauriPlatformAdapter,
  type TauriPluginListener,
  type TauriPushToken,
  type TauriPushTokenResult,
  type TauriPushTokenSource,
  type TauriPushNotificationsAdapter,
  type TauriSecureStoreAdapter,
  type TauriMobileProductStorageNames,
  type TauriStrongholdAdapter,
  type TauriStrongholdClient,
  type TauriStrongholdHandle,
  type TauriStrongholdPassword,
  type TauriStrongholdStore,
  type TauriStoreAdapter,
  type TauriStoreHandle,
} from "./tauri-bridge.ts";
