export const deployControlLogicalTables = [
  "runnerProfiles",
  "spaces",
  "projects",
  "sources",
  "sourceSnapshots",
  "connections",
  "secretBlobs",
  "installConfigs",
  "installations",
  "capsuleCompatibilityReports",
  "providerEnvBindingSets",
  "installationDependencies",
  "dependencySnapshots",
  "outputSnapshots",
  "outputShares",
  "runGroups",
  "runs",
  "runsInputs",
  "stateSnapshots",
  "deployments",
  "artifacts",
  "billingPlans",
  "billingAccounts",
  "spaceSubscriptions",
  "creditBalances",
  "billingAutoRechargeAttempts",
  "usageEvents",
  "creditReservations",
  "credentialMintEvents",
  "securityFindings",
  "auditEvents",
  "backups",
  // Resource Shape flow (`takosumi.dev/v1alpha1`): the durable projections of
  // Resource / ResolutionLock / TargetPool / SpacePolicy live on the same
  // deploy-control plane as the Flow A ledger (`final-plan.md` §10).
  "resourceShapes",
  "resolutionLocks",
  "targetPools",
  "spacePolicies",
] as const;

export type DeployControlLogicalTable =
  (typeof deployControlLogicalTables)[number];

export const deployControlD1TableNames = {
  runnerProfiles: "runner_profiles",
  // P4 17-noun rename: physical table renamed `spaces` -> `workspaces`. The
  // logical key (and the Drizzle export) stays `spaces` until convergence
  // (slice 7) renames the TS identifiers; only the physical name string moves.
  spaces: "workspaces",
  projects: "projects",
  sources: "sources",
  sourceSnapshots: "source_snapshots",
  connections: "connections",
  secretBlobs: "secret_blobs",
  installConfigs: "install_configs",
  installations: "capsules",
  capsuleCompatibilityReports: "capsule_compatibility_reports",
  providerEnvBindingSets: "provider_env_binding_sets",
  installationDependencies: "installation_dependencies",
  dependencySnapshots: "dependency_snapshots",
  outputSnapshots: "outputs",
  outputShares: "output_shares",
  runGroups: "run_groups",
  runs: "runs",
  runsInputs: "runs_inputs",
  stateSnapshots: "state_versions",
  deployments: "deployments",
  artifacts: "artifacts",
  billingPlans: "plans",
  billingAccounts: "billing_accounts",
  spaceSubscriptions: "space_subscriptions",
  creditBalances: "credit_balances",
  billingAutoRechargeAttempts: "billing_auto_recharge_attempts",
  usageEvents: "usage_events",
  creditReservations: "credit_reservations",
  credentialMintEvents: "credential_mint_events",
  securityFindings: "security_findings",
  auditEvents: "audit_events",
  backups: "backups",
  resourceShapes: "resource_shapes",
  resolutionLocks: "resolution_locks",
  targetPools: "target_pools",
  spacePolicies: "space_policies",
} as const satisfies Record<DeployControlLogicalTable, string>;

export const deployControlPostgresTableNames = {
  runnerProfiles: "takosumi_runner_profiles",
  // P4 17-noun rename: physical table `takosumi_spaces` -> `takosumi_workspaces`
  // (logical key / Drizzle export stays `spaces` until convergence).
  spaces: "takosumi_workspaces",
  projects: "takosumi_projects",
  sources: "takosumi_sources",
  sourceSnapshots: "takosumi_source_snapshots",
  connections: "takosumi_connections",
  secretBlobs: "takosumi_connection_secret_blobs",
  installConfigs: "takosumi_install_configs",
  installations: "takosumi_capsules",
  capsuleCompatibilityReports: "takosumi_capsule_compatibility_reports",
  providerEnvBindingSets: "takosumi_provider_env_binding_sets",
  installationDependencies: "takosumi_installation_dependencies",
  dependencySnapshots: "takosumi_dependency_snapshots",
  outputSnapshots: "takosumi_outputs",
  outputShares: "takosumi_output_shares",
  runGroups: "takosumi_run_groups",
  runs: "takosumi_runs",
  runsInputs: "takosumi_plan_run_inputs",
  stateSnapshots: "takosumi_state_versions",
  deployments: "takosumi_opentofu_deployments",
  artifacts: "takosumi_artifacts",
  billingPlans: "takosumi_plans",
  billingAccounts: "takosumi_billing_accounts",
  spaceSubscriptions: "takosumi_space_subscriptions",
  creditBalances: "takosumi_credit_balances",
  billingAutoRechargeAttempts: "takosumi_billing_auto_recharge_attempts",
  usageEvents: "takosumi_usage_events",
  creditReservations: "takosumi_credit_reservations",
  credentialMintEvents: "takosumi_credential_mint_events",
  securityFindings: "takosumi_security_findings",
  auditEvents: "takosumi_audit_events",
  backups: "takosumi_backups",
  resourceShapes: "takosumi_resource_shapes",
  resolutionLocks: "takosumi_resolution_locks",
  targetPools: "takosumi_target_pools",
  spacePolicies: "takosumi_space_policies",
} as const satisfies Record<DeployControlLogicalTable, string>;
