export const deployControlLogicalTables = [
  "runnerProfiles",
  "workspaces",
  "workspaceMembers",
  "projects",
  "sources",
  "sourceSnapshots",
  "connections",
  "secretBlobs",
  "installConfigs",
  "capsules",
  "capsuleCompatibilityReports",
  "providerBindingSets",
  "dependencies",
  "dependencySnapshots",
  "outputs",
  "outputShares",
  "runGroups",
  "runs",
  "planRunInputs",
  "stateVersions",
  "artifacts",
  "usageEvents",
  "publicHostReservations",
  "credentialMintEvents",
  "securityFindings",
  "auditEvents",
  "backups",
  // Resource Shape flow (`takosumi.dev/v1alpha1`): the durable projections of
  // Resource / ResolutionLock / TargetPool / SpacePolicy live on the same
  // deploy-control plane as the Flow A ledger (`final-plan.md` §10).
  "resourceShapes",
  "resolutionLocks",
  "targetPools",
  "spacePolicies",
  // Runtime declaration layer shared by Capsule and Resource authoring flows.
  "interfaces",
  "interfaceBindings",
  // Portable Service Form host registry. Takosumi may start with all three
  // tables empty; installed packages are optional host contributions.
  "serviceFormPackages",
  "serviceFormDefinitions",
  "serviceFormActivations",
] as const;

export type DeployControlLogicalTable =
  (typeof deployControlLogicalTables)[number];

export const deployControlD1TableNames = {
  runnerProfiles: "runner_profiles",
  workspaces: "workspaces",
  workspaceMembers: "workspace_members",
  projects: "projects",
  sources: "sources",
  sourceSnapshots: "source_snapshots",
  connections: "connections",
  secretBlobs: "secret_blobs",
  installConfigs: "install_configs",
  capsules: "capsules",
  capsuleCompatibilityReports: "capsule_compatibility_reports",
  providerBindingSets: "provider_env_binding_sets",
  dependencies: "installation_dependencies",
  dependencySnapshots: "dependency_snapshots",
  outputs: "outputs",
  outputShares: "output_shares",
  runGroups: "run_groups",
  runs: "runs",
  planRunInputs: "runs_inputs",
  stateVersions: "state_versions",
  artifacts: "artifacts",
  usageEvents: "usage_events",
  publicHostReservations: "public_host_reservations",
  credentialMintEvents: "credential_mint_events",
  securityFindings: "security_findings",
  auditEvents: "audit_events",
  backups: "backups",
  resourceShapes: "resource_shapes",
  resolutionLocks: "resolution_locks",
  targetPools: "target_pools",
  spacePolicies: "space_policies",
  interfaces: "interfaces",
  interfaceBindings: "interface_bindings",
  serviceFormPackages: "service_form_packages",
  serviceFormDefinitions: "service_form_definitions",
  serviceFormActivations: "service_form_activations",
} as const satisfies Record<DeployControlLogicalTable, string>;

export const deployControlPostgresTableNames = {
  runnerProfiles: "takosumi_runner_profiles",
  workspaces: "takosumi_workspaces",
  workspaceMembers: "takosumi_workspace_members",
  projects: "takosumi_projects",
  sources: "takosumi_sources",
  sourceSnapshots: "takosumi_source_snapshots",
  connections: "takosumi_connections",
  secretBlobs: "takosumi_connection_secret_blobs",
  installConfigs: "takosumi_install_configs",
  capsules: "takosumi_capsules",
  capsuleCompatibilityReports: "takosumi_capsule_compatibility_reports",
  providerBindingSets: "takosumi_provider_env_binding_sets",
  dependencies: "takosumi_installation_dependencies",
  dependencySnapshots: "takosumi_dependency_snapshots",
  outputs: "takosumi_outputs",
  outputShares: "takosumi_output_shares",
  runGroups: "takosumi_run_groups",
  runs: "takosumi_runs",
  planRunInputs: "takosumi_plan_run_inputs",
  stateVersions: "takosumi_state_versions",
  artifacts: "takosumi_artifacts",
  usageEvents: "takosumi_usage_events",
  publicHostReservations: "takosumi_public_host_reservations",
  credentialMintEvents: "takosumi_credential_mint_events",
  securityFindings: "takosumi_security_findings",
  auditEvents: "takosumi_audit_events",
  backups: "takosumi_backups",
  resourceShapes: "takosumi_resource_shapes",
  resolutionLocks: "takosumi_resolution_locks",
  targetPools: "takosumi_target_pools",
  spacePolicies: "takosumi_space_policies",
  interfaces: "takosumi_interfaces",
  interfaceBindings: "takosumi_interface_bindings",
  serviceFormPackages: "takosumi_service_form_packages",
  serviceFormDefinitions: "takosumi_service_form_definitions",
  serviceFormActivations: "takosumi_service_form_activations",
} as const satisfies Record<DeployControlLogicalTable, string>;
