// Generated by scripts/build-credential-recipe-assets.ts. Do not edit.
import type { CredentialRecipe } from "../contract/credential-recipes.ts";

export const REFERENCE_CREDENTIAL_RECIPES: readonly CredentialRecipe[] = [
  {
    "id": "aws",
    "displayName": "AWS",
    "secretPartition": "provider-credentials",
    "terraformSource": [
      "hashicorp/aws",
      "registry.opentofu.org/hashicorp/aws"
    ],
    "envNames": [
      "AWS_ACCESS_KEY_ID",
      "AWS_SECRET_ACCESS_KEY",
      "AWS_SESSION_TOKEN",
      "AWS_WEB_IDENTITY_TOKEN_FILE",
      "AWS_ROLE_ARN",
      "AWS_REGION",
      "AWS_DEFAULT_REGION",
      "AWS_ENDPOINT_URL_S3"
    ],
    "requiredEnvGroups": [
      [
        "AWS_ACCESS_KEY_ID",
        "AWS_SECRET_ACCESS_KEY"
      ],
      [
        "AWS_WEB_IDENTITY_TOKEN_FILE",
        "AWS_ROLE_ARN"
      ]
    ],
    "authModes": {
      "static_keys": {
        "env": {
          "AWS_ACCESS_KEY_ID": {
            "from": "secret",
            "name": "access_key_id"
          },
          "AWS_SECRET_ACCESS_KEY": {
            "from": "secret",
            "name": "secret_access_key"
          },
          "AWS_SESSION_TOKEN": {
            "from": "secret",
            "name": "session_token"
          },
          "AWS_REGION": {
            "from": "value",
            "name": "region"
          },
          "AWS_DEFAULT_REGION": {
            "from": "value",
            "name": "region"
          }
        },
        "inputHints": {
          "AWS_ACCESS_KEY_ID": {
            "label": {
              "en": "Access key ID",
              "ja": "アクセスキー ID"
            },
            "placeholder": "AKIA...",
            "required": true
          },
          "AWS_SECRET_ACCESS_KEY": {
            "label": {
              "en": "Secret access key",
              "ja": "シークレットアクセスキー"
            },
            "required": true
          },
          "AWS_SESSION_TOKEN": {
            "label": {
              "en": "Session token",
              "ja": "セッショントークン"
            },
            "required": false
          },
          "AWS_REGION": {
            "label": {
              "en": "Region",
              "ja": "リージョン"
            },
            "placeholder": "ap-northeast-1",
            "required": false
          },
          "AWS_DEFAULT_REGION": {
            "hidden": true
          }
        },
        "presentation": {
          "showInConnectionSetup": true,
          "displayName": {
            "en": "Static access keys",
            "ja": "静的アクセスキー"
          },
          "setupGuide": {
            "url": "https://console.aws.amazon.com/iam/home#/users",
            "steps": [
              {
                "en": "Open IAM and select the user used for OpenTofu.",
                "ja": "IAM を開き、OpenTofu で使うユーザーを選びます。"
              },
              {
                "en": "Create an access key with only the permissions this stack needs.",
                "ja": "この Stack に必要な権限だけを持つアクセスキーを作成します。"
              },
              {
                "en": "Copy the access key ID and secret access key into this form.",
                "ja": "アクセスキー ID とシークレットアクセスキーをこのフォームへ入力します。"
              }
            ]
          }
        }
      },
      "assume_role": {
        "env": {
          "AWS_ACCESS_KEY_ID": {
            "from": "generated",
            "name": "access_key_id"
          },
          "AWS_SECRET_ACCESS_KEY": {
            "from": "generated",
            "name": "secret_access_key"
          },
          "AWS_SESSION_TOKEN": {
            "from": "generated",
            "name": "session_token"
          },
          "AWS_REGION": {
            "from": "value",
            "name": "region"
          },
          "AWS_DEFAULT_REGION": {
            "from": "value",
            "name": "region"
          }
        },
        "preRun": {
          "type": "aws_sts_assume_role",
          "inputs": {
            "role_arn": {
              "from": "value",
              "name": "role_arn"
            }
          }
        }
      },
      "web_identity": {
        "env": {
          "AWS_WEB_IDENTITY_TOKEN_FILE": {
            "from": "value",
            "name": "token_file"
          },
          "AWS_ROLE_ARN": {
            "from": "value",
            "name": "role_arn"
          },
          "AWS_REGION": {
            "from": "value",
            "name": "region"
          }
        }
      }
    }
  },
  {
    "id": "azurerm",
    "displayName": "Azure Resource Manager",
    "secretPartition": "provider-credentials",
    "terraformSource": [
      "hashicorp/azurerm",
      "registry.opentofu.org/hashicorp/azurerm"
    ],
    "envNames": [
      "ARM_CLIENT_ID",
      "ARM_CLIENT_SECRET",
      "ARM_TENANT_ID",
      "ARM_SUBSCRIPTION_ID",
      "AZURE_CLIENT_ID",
      "AZURE_CLIENT_SECRET",
      "AZURE_TENANT_ID",
      "AZURE_SUBSCRIPTION_ID"
    ],
    "requiredEnvGroups": [
      [
        "ARM_CLIENT_ID",
        "ARM_CLIENT_SECRET",
        "ARM_TENANT_ID",
        "ARM_SUBSCRIPTION_ID"
      ],
      [
        "AZURE_CLIENT_ID",
        "AZURE_CLIENT_SECRET",
        "AZURE_TENANT_ID",
        "AZURE_SUBSCRIPTION_ID"
      ]
    ],
    "authModes": {
      "arm_client_secret": {
        "env": {
          "ARM_CLIENT_ID": {
            "from": "value",
            "name": "client_id"
          },
          "ARM_CLIENT_SECRET": {
            "from": "secret",
            "name": "client_secret"
          },
          "ARM_TENANT_ID": {
            "from": "value",
            "name": "tenant_id"
          },
          "ARM_SUBSCRIPTION_ID": {
            "from": "value",
            "name": "subscription_id"
          }
        },
        "inputHints": {
          "ARM_CLIENT_ID": {
            "label": {
              "en": "Client ID",
              "ja": "クライアント ID"
            },
            "required": true
          },
          "ARM_CLIENT_SECRET": {
            "label": {
              "en": "Client secret",
              "ja": "クライアントシークレット"
            },
            "required": true
          },
          "ARM_TENANT_ID": {
            "label": {
              "en": "Tenant ID",
              "ja": "テナント ID"
            },
            "required": true
          },
          "ARM_SUBSCRIPTION_ID": {
            "label": {
              "en": "Subscription ID",
              "ja": "サブスクリプション ID"
            },
            "required": true
          }
        },
        "presentation": {
          "showInConnectionSetup": true,
          "displayName": {
            "en": "ARM client secret",
            "ja": "ARM クライアントシークレット"
          }
        }
      },
      "azure_client_secret": {
        "env": {
          "AZURE_CLIENT_ID": {
            "from": "value",
            "name": "client_id"
          },
          "AZURE_CLIENT_SECRET": {
            "from": "secret",
            "name": "client_secret"
          },
          "AZURE_TENANT_ID": {
            "from": "value",
            "name": "tenant_id"
          },
          "AZURE_SUBSCRIPTION_ID": {
            "from": "value",
            "name": "subscription_id"
          }
        },
        "inputHints": {
          "AZURE_CLIENT_ID": {
            "label": {
              "en": "Client ID",
              "ja": "クライアント ID"
            },
            "required": true
          },
          "AZURE_CLIENT_SECRET": {
            "label": {
              "en": "Client secret",
              "ja": "クライアントシークレット"
            },
            "required": true
          },
          "AZURE_TENANT_ID": {
            "label": {
              "en": "Tenant ID",
              "ja": "テナント ID"
            },
            "required": true
          },
          "AZURE_SUBSCRIPTION_ID": {
            "label": {
              "en": "Subscription ID",
              "ja": "サブスクリプション ID"
            },
            "required": true
          }
        },
        "presentation": {
          "showInConnectionSetup": true,
          "displayName": {
            "en": "Azure client secret variables",
            "ja": "Azure クライアントシークレット変数"
          }
        }
      }
    }
  },
  {
    "id": "cloudflare",
    "displayName": "Cloudflare",
    "secretPartition": "provider-credentials",
    "terraformSource": [
      "cloudflare/cloudflare",
      "registry.opentofu.org/cloudflare/cloudflare"
    ],
    "envNames": [
      "CLOUDFLARE_API_TOKEN",
      "CLOUDFLARE_API_KEY",
      "CLOUDFLARE_EMAIL",
      "CLOUDFLARE_ACCOUNT_ID",
      "CLOUDFLARE_ZONE_ID",
      "CF_API_TOKEN"
    ],
    "requiredEnvGroups": [
      [
        "CLOUDFLARE_API_TOKEN"
      ],
      [
        "CF_API_TOKEN"
      ],
      [
        "CLOUDFLARE_API_KEY",
        "CLOUDFLARE_EMAIL"
      ]
    ],
    "authModes": {
      "oauth": {
        "env": {
          "CLOUDFLARE_API_TOKEN": {
            "from": "secret",
            "name": "access_token"
          }
        }
      },
      "api_token": {
        "env": {
          "CLOUDFLARE_API_TOKEN": {
            "from": "secret",
            "name": "api_token"
          },
          "CLOUDFLARE_ACCOUNT_ID": {
            "from": "value",
            "name": "account_id"
          },
          "CLOUDFLARE_ZONE_ID": {
            "from": "value",
            "name": "zone_id"
          }
        },
        "inputHints": {
          "CLOUDFLARE_API_TOKEN": {
            "label": {
              "en": "API token",
              "ja": "API トークン"
            },
            "required": true
          },
          "CLOUDFLARE_ACCOUNT_ID": {
            "label": {
              "en": "Account ID",
              "ja": "アカウント ID"
            },
            "placeholder": "0123abcd...",
            "required": false
          },
          "CLOUDFLARE_ZONE_ID": {
            "label": {
              "en": "Zone ID",
              "ja": "ゾーン ID"
            },
            "required": false
          }
        },
        "presentation": {
          "showInConnectionSetup": true,
          "displayName": {
            "en": "API token",
            "ja": "API トークン"
          },
          "setupGuide": {
            "url": "https://dash.cloudflare.com/profile/api-tokens",
            "steps": [
              {
                "en": "Open the API Tokens page in Cloudflare.",
                "ja": "Cloudflare の API Tokens 画面を開きます。"
              },
              {
                "en": "Create a token with only the permissions required by this stack.",
                "ja": "この Stack に必要な権限だけを持つトークンを作成します。"
              },
              {
                "en": "Copy the token and any optional account or zone scope below.",
                "ja": "トークンと、必要ならアカウントまたはゾーンの範囲を入力します。"
              }
            ]
          }
        }
      },
      "cf_api_token": {
        "env": {
          "CF_API_TOKEN": {
            "from": "secret",
            "name": "api_token"
          }
        },
        "inputHints": {
          "CF_API_TOKEN": {
            "label": {
              "en": "API token",
              "ja": "API トークン"
            },
            "required": true
          }
        },
        "presentation": {
          "showInConnectionSetup": true,
          "displayName": {
            "en": "CF API token",
            "ja": "CF API トークン"
          }
        }
      },
      "global_key": {
        "env": {
          "CLOUDFLARE_API_KEY": {
            "from": "secret",
            "name": "api_key"
          },
          "CLOUDFLARE_EMAIL": {
            "from": "value",
            "name": "email"
          }
        },
        "inputHints": {
          "CLOUDFLARE_API_KEY": {
            "label": {
              "en": "Global API key",
              "ja": "Global API キー"
            },
            "required": true
          },
          "CLOUDFLARE_EMAIL": {
            "label": {
              "en": "Account email",
              "ja": "アカウントメールアドレス"
            },
            "required": true
          }
        },
        "presentation": {
          "showInConnectionSetup": true,
          "displayName": {
            "en": "Global API key",
            "ja": "Global API キー"
          }
        }
      }
    }
  },
  {
    "id": "digitalocean",
    "displayName": "DigitalOcean",
    "secretPartition": "provider-credentials",
    "terraformSource": [
      "digitalocean/digitalocean",
      "registry.opentofu.org/digitalocean/digitalocean"
    ],
    "envNames": [
      "DIGITALOCEAN_TOKEN",
      "SPACES_ACCESS_KEY_ID",
      "SPACES_SECRET_ACCESS_KEY"
    ],
    "requiredEnvGroups": [
      [
        "DIGITALOCEAN_TOKEN"
      ]
    ],
    "authModes": {
      "token": {
        "env": {
          "DIGITALOCEAN_TOKEN": {
            "from": "secret",
            "name": "token"
          }
        },
        "inputHints": {
          "DIGITALOCEAN_TOKEN": {
            "label": {
              "en": "API token",
              "ja": "API トークン"
            },
            "required": true
          }
        },
        "presentation": {
          "showInConnectionSetup": true,
          "displayName": {
            "en": "API token",
            "ja": "API トークン"
          }
        }
      },
      "spaces": {
        "env": {
          "DIGITALOCEAN_TOKEN": {
            "from": "secret",
            "name": "token"
          },
          "SPACES_ACCESS_KEY_ID": {
            "from": "secret",
            "name": "spaces_access_key_id"
          },
          "SPACES_SECRET_ACCESS_KEY": {
            "from": "secret",
            "name": "spaces_secret_access_key"
          }
        },
        "inputHints": {
          "DIGITALOCEAN_TOKEN": {
            "label": {
              "en": "API token",
              "ja": "API トークン"
            },
            "required": true
          },
          "SPACES_ACCESS_KEY_ID": {
            "label": {
              "en": "Spaces access key ID",
              "ja": "Spaces アクセスキー ID"
            },
            "required": true
          },
          "SPACES_SECRET_ACCESS_KEY": {
            "label": {
              "en": "Spaces secret access key",
              "ja": "Spaces シークレットアクセスキー"
            },
            "required": true
          }
        },
        "presentation": {
          "showInConnectionSetup": true,
          "displayName": {
            "en": "API token and Spaces keys",
            "ja": "API トークンと Spaces キー"
          }
        }
      }
    }
  },
  {
    "id": "generic-env",
    "displayName": "Generic environment variables",
    "secretPartition": "provider-credentials",
    "terraformSource": "*",
    "declaredEnv": true,
    "authModes": {
      "env": {
        "env": {
          "*": {
            "from": "user_defined"
          }
        },
        "files": {
          "*": {
            "from": "user_defined"
          }
        }
      }
    }
  },
  {
    "id": "github",
    "displayName": "GitHub",
    "secretPartition": "provider-credentials",
    "terraformSource": [
      "integrations/github",
      "github/github",
      "registry.opentofu.org/integrations/github",
      "registry.opentofu.org/github/github"
    ],
    "envNames": [
      "GITHUB_TOKEN"
    ],
    "requiredEnvGroups": [
      [
        "GITHUB_TOKEN"
      ]
    ],
    "authModes": {
      "token": {
        "env": {
          "GITHUB_TOKEN": {
            "from": "secret",
            "name": "token"
          }
        },
        "inputHints": {
          "GITHUB_TOKEN": {
            "label": {
              "en": "Token",
              "ja": "トークン"
            },
            "required": true
          }
        },
        "presentation": {
          "showInConnectionSetup": true,
          "displayName": {
            "en": "Personal access token",
            "ja": "Personal access token"
          }
        }
      }
    }
  },
  {
    "id": "google",
    "displayName": "Google Cloud",
    "secretPartition": "provider-credentials",
    "terraformSource": [
      "hashicorp/google",
      "hashicorp/google-beta",
      "registry.opentofu.org/hashicorp/google",
      "registry.opentofu.org/hashicorp/google-beta"
    ],
    "envNames": [
      "GOOGLE_CREDENTIALS",
      "GOOGLE_APPLICATION_CREDENTIALS",
      "GOOGLE_CLOUD_PROJECT",
      "GOOGLE_PROJECT",
      "GOOGLE_REGION"
    ],
    "requiredEnvGroups": [
      [
        "GOOGLE_CREDENTIALS"
      ],
      [
        "GOOGLE_APPLICATION_CREDENTIALS"
      ]
    ],
    "authModes": {
      "oauth": {
        "env": {
          "GOOGLE_CREDENTIALS": {
            "from": "secret",
            "name": "authorized_user_json"
          }
        }
      },
      "service_account_json": {
        "env": {
          "GOOGLE_CREDENTIALS": {
            "from": "secret",
            "name": "service_account_json"
          },
          "GOOGLE_CLOUD_PROJECT": {
            "from": "value",
            "name": "project_id"
          },
          "GOOGLE_PROJECT": {
            "from": "value",
            "name": "project_id"
          },
          "GOOGLE_REGION": {
            "from": "value",
            "name": "region"
          }
        },
        "inputHints": {
          "GOOGLE_CREDENTIALS": {
            "label": {
              "en": "Service account JSON",
              "ja": "サービスアカウント JSON"
            },
            "required": true
          },
          "GOOGLE_CLOUD_PROJECT": {
            "label": {
              "en": "Project ID",
              "ja": "プロジェクト ID"
            },
            "placeholder": "my-project",
            "required": false
          },
          "GOOGLE_PROJECT": {
            "hidden": true
          },
          "GOOGLE_REGION": {
            "label": {
              "en": "Region",
              "ja": "リージョン"
            },
            "required": false
          }
        },
        "presentation": {
          "showInConnectionSetup": true,
          "displayName": {
            "en": "Service account JSON",
            "ja": "サービスアカウント JSON"
          },
          "setupGuide": {
            "url": "https://console.cloud.google.com/iam-admin/serviceaccounts",
            "steps": [
              {
                "en": "Open Service Accounts and select the account used by OpenTofu.",
                "ja": "Service Accounts を開き、OpenTofu で使うアカウントを選びます。"
              },
              {
                "en": "Create a JSON key with only the roles required by this stack.",
                "ja": "この Stack に必要なロールだけを持つ JSON キーを作成します。"
              },
              {
                "en": "Paste the complete JSON document below.",
                "ja": "完全な JSON ドキュメントを下へ貼り付けます。"
              }
            ]
          }
        }
      },
      "service_account_file": {
        "env": {
          "GOOGLE_APPLICATION_CREDENTIALS": {
            "from": "literal",
            "value": "/run/takosumi/google-credentials.json"
          },
          "GOOGLE_PROJECT": {
            "from": "value",
            "name": "project_id"
          }
        },
        "files": {
          "google-credentials.json": {
            "from": "secret",
            "name": "service_account_json",
            "envName": "GOOGLE_APPLICATION_CREDENTIALS",
            "mode": 384
          }
        }
      },
      "impersonation": {
        "env": {
          "GOOGLE_CREDENTIALS": {
            "from": "generated",
            "name": "access_token_json"
          },
          "GOOGLE_CLOUD_PROJECT": {
            "from": "value",
            "name": "project_id"
          }
        },
        "preRun": {
          "type": "gcp_service_account_impersonation",
          "inputs": {
            "service_account_email": {
              "from": "value",
              "name": "service_account_email"
            }
          }
        }
      }
    }
  },
  {
    "id": "hcloud",
    "displayName": "Hetzner Cloud",
    "secretPartition": "provider-credentials",
    "terraformSource": [
      "hetznercloud/hcloud",
      "registry.opentofu.org/hetznercloud/hcloud"
    ],
    "envNames": [
      "HCLOUD_TOKEN"
    ],
    "requiredEnvGroups": [
      [
        "HCLOUD_TOKEN"
      ]
    ],
    "authModes": {
      "token": {
        "env": {
          "HCLOUD_TOKEN": {
            "from": "secret",
            "name": "token"
          }
        },
        "inputHints": {
          "HCLOUD_TOKEN": {
            "label": {
              "en": "API token",
              "ja": "API トークン"
            },
            "required": true
          }
        },
        "presentation": {
          "showInConnectionSetup": true,
          "displayName": {
            "en": "API token",
            "ja": "API トークン"
          },
          "setupGuide": {
            "url": "https://console.hetzner.cloud/",
            "steps": [
              {
                "en": "Open the Hetzner Cloud project used by this stack.",
                "ja": "この Stack で使う Hetzner Cloud プロジェクトを開きます。"
              },
              {
                "en": "Create a project API token with the required permissions.",
                "ja": "必要な権限を持つプロジェクト API トークンを作成します。"
              },
              {
                "en": "Copy the token below.",
                "ja": "トークンを下へ入力します。"
              }
            ]
          }
        }
      }
    }
  },
  {
    "id": "helm",
    "displayName": "Helm",
    "secretPartition": "provider-credentials",
    "terraformSource": [
      "hashicorp/helm",
      "registry.opentofu.org/hashicorp/helm"
    ],
    "envNames": [
      "KUBE_CONFIG_PATH",
      "KUBE_HOST",
      "KUBE_TOKEN",
      "KUBE_CLUSTER_CA_CERT_DATA"
    ],
    "requiredEnvGroups": [
      [
        "KUBE_CONFIG_PATH"
      ],
      [
        "KUBE_HOST",
        "KUBE_TOKEN"
      ]
    ],
    "authModes": {
      "kubeconfig": {
        "env": {
          "KUBE_CONFIG_PATH": {
            "from": "value",
            "name": "kubeconfig_path"
          }
        }
      },
      "token": {
        "env": {
          "KUBE_HOST": {
            "from": "value",
            "name": "host"
          },
          "KUBE_TOKEN": {
            "from": "secret",
            "name": "token"
          },
          "KUBE_CLUSTER_CA_CERT_DATA": {
            "from": "secret",
            "name": "cluster_ca_cert_data"
          }
        },
        "inputHints": {
          "KUBE_HOST": {
            "label": {
              "en": "Cluster endpoint",
              "ja": "クラスター endpoint"
            },
            "placeholder": "https://cluster.example.com",
            "required": true
          },
          "KUBE_TOKEN": {
            "label": {
              "en": "Bearer token",
              "ja": "Bearer トークン"
            },
            "required": true
          },
          "KUBE_CLUSTER_CA_CERT_DATA": {
            "label": {
              "en": "Cluster CA certificate data",
              "ja": "クラスター CA 証明書データ"
            },
            "required": false
          }
        },
        "presentation": {
          "showInConnectionSetup": true,
          "displayName": {
            "en": "Cluster endpoint and token",
            "ja": "クラスター endpoint とトークン"
          }
        }
      }
    }
  },
  {
    "id": "kubernetes",
    "displayName": "Kubernetes",
    "secretPartition": "provider-credentials",
    "terraformSource": [
      "hashicorp/kubernetes",
      "registry.opentofu.org/hashicorp/kubernetes"
    ],
    "envNames": [
      "KUBE_CONFIG_PATH",
      "KUBE_HOST",
      "KUBE_TOKEN",
      "KUBE_CLUSTER_CA_CERT_DATA"
    ],
    "requiredEnvGroups": [
      [
        "KUBE_CONFIG_PATH"
      ],
      [
        "KUBE_HOST",
        "KUBE_TOKEN"
      ]
    ],
    "authModes": {
      "kubeconfig": {
        "env": {
          "KUBE_CONFIG_PATH": {
            "from": "value",
            "name": "kubeconfig_path"
          }
        }
      },
      "token": {
        "env": {
          "KUBE_HOST": {
            "from": "value",
            "name": "host"
          },
          "KUBE_TOKEN": {
            "from": "secret",
            "name": "token"
          },
          "KUBE_CLUSTER_CA_CERT_DATA": {
            "from": "secret",
            "name": "cluster_ca_cert_data"
          }
        },
        "inputHints": {
          "KUBE_HOST": {
            "label": {
              "en": "Cluster endpoint",
              "ja": "クラスター endpoint"
            },
            "placeholder": "https://cluster.example.com",
            "required": true
          },
          "KUBE_TOKEN": {
            "label": {
              "en": "Bearer token",
              "ja": "Bearer トークン"
            },
            "required": true
          },
          "KUBE_CLUSTER_CA_CERT_DATA": {
            "label": {
              "en": "Cluster CA certificate data",
              "ja": "クラスター CA 証明書データ"
            },
            "required": false
          }
        },
        "presentation": {
          "showInConnectionSetup": true,
          "displayName": {
            "en": "Cluster endpoint and token",
            "ja": "クラスター endpoint とトークン"
          }
        }
      }
    }
  },
  {
    "id": "openstack",
    "displayName": "OpenStack",
    "secretPartition": "provider-credentials",
    "terraformSource": [
      "terraform-provider-openstack/openstack",
      "registry.opentofu.org/terraform-provider-openstack/openstack"
    ],
    "envNames": [
      "OS_CLOUD",
      "OS_AUTH_URL",
      "OS_USERNAME",
      "OS_PASSWORD",
      "OS_PROJECT_NAME",
      "OS_USER_DOMAIN_NAME",
      "OS_PROJECT_DOMAIN_NAME",
      "OS_REGION_NAME",
      "OS_APPLICATION_CREDENTIAL_ID",
      "OS_APPLICATION_CREDENTIAL_SECRET"
    ],
    "requiredEnvGroups": [
      [
        "OS_CLOUD"
      ],
      [
        "OS_AUTH_URL",
        "OS_USERNAME",
        "OS_PASSWORD",
        "OS_PROJECT_NAME"
      ],
      [
        "OS_AUTH_URL",
        "OS_APPLICATION_CREDENTIAL_ID",
        "OS_APPLICATION_CREDENTIAL_SECRET"
      ]
    ],
    "authModes": {
      "cloud_profile": {
        "env": {
          "OS_CLOUD": {
            "from": "value",
            "name": "cloud"
          }
        }
      },
      "password": {
        "env": {
          "OS_AUTH_URL": {
            "from": "value",
            "name": "auth_url"
          },
          "OS_USERNAME": {
            "from": "value",
            "name": "username"
          },
          "OS_PASSWORD": {
            "from": "secret",
            "name": "password"
          },
          "OS_PROJECT_NAME": {
            "from": "value",
            "name": "project_name"
          },
          "OS_USER_DOMAIN_NAME": {
            "from": "value",
            "name": "user_domain_name"
          },
          "OS_PROJECT_DOMAIN_NAME": {
            "from": "value",
            "name": "project_domain_name"
          },
          "OS_REGION_NAME": {
            "from": "value",
            "name": "region"
          }
        },
        "inputHints": {
          "OS_AUTH_URL": {
            "label": {
              "en": "Identity endpoint",
              "ja": "Identity endpoint"
            },
            "placeholder": "https://identity.example.com/v3",
            "required": true
          },
          "OS_USERNAME": {
            "label": {
              "en": "Username",
              "ja": "ユーザー名"
            },
            "required": true
          },
          "OS_PASSWORD": {
            "label": {
              "en": "Password",
              "ja": "パスワード"
            },
            "required": true
          },
          "OS_PROJECT_NAME": {
            "label": {
              "en": "Project name",
              "ja": "プロジェクト名"
            },
            "required": true
          },
          "OS_USER_DOMAIN_NAME": {
            "label": {
              "en": "User domain",
              "ja": "ユーザードメイン"
            },
            "required": false
          },
          "OS_PROJECT_DOMAIN_NAME": {
            "label": {
              "en": "Project domain",
              "ja": "プロジェクトドメイン"
            },
            "required": false
          },
          "OS_REGION_NAME": {
            "label": {
              "en": "Region",
              "ja": "リージョン"
            },
            "required": false
          }
        },
        "presentation": {
          "showInConnectionSetup": true,
          "displayName": {
            "en": "Username and password",
            "ja": "ユーザー名とパスワード"
          }
        }
      },
      "application_credential": {
        "env": {
          "OS_AUTH_URL": {
            "from": "value",
            "name": "auth_url"
          },
          "OS_APPLICATION_CREDENTIAL_ID": {
            "from": "secret",
            "name": "application_credential_id"
          },
          "OS_APPLICATION_CREDENTIAL_SECRET": {
            "from": "secret",
            "name": "application_credential_secret"
          },
          "OS_REGION_NAME": {
            "from": "value",
            "name": "region"
          }
        },
        "inputHints": {
          "OS_AUTH_URL": {
            "label": {
              "en": "Identity endpoint",
              "ja": "Identity endpoint"
            },
            "placeholder": "https://identity.example.com/v3",
            "required": true
          },
          "OS_APPLICATION_CREDENTIAL_ID": {
            "label": {
              "en": "Application credential ID",
              "ja": "Application credential ID"
            },
            "required": true
          },
          "OS_APPLICATION_CREDENTIAL_SECRET": {
            "label": {
              "en": "Application credential secret",
              "ja": "Application credential secret"
            },
            "required": true
          },
          "OS_REGION_NAME": {
            "label": {
              "en": "Region",
              "ja": "リージョン"
            },
            "required": false
          }
        },
        "presentation": {
          "showInConnectionSetup": true,
          "displayName": {
            "en": "Application credential",
            "ja": "Application credential"
          }
        }
      }
    }
  },
  {
    "id": "s3-compatible",
    "displayName": "S3-compatible object storage",
    "secretPartition": "provider-credentials",
    "terraformSource": [
      "hashicorp/aws",
      "registry.opentofu.org/hashicorp/aws"
    ],
    "envNames": [
      "AWS_ACCESS_KEY_ID",
      "AWS_SECRET_ACCESS_KEY",
      "AWS_REGION",
      "AWS_DEFAULT_REGION",
      "AWS_ENDPOINT_URL_S3"
    ],
    "requiredEnvGroups": [
      [
        "AWS_ACCESS_KEY_ID",
        "AWS_SECRET_ACCESS_KEY"
      ]
    ],
    "authModes": {
      "static_keys_with_endpoint": {
        "env": {
          "AWS_ACCESS_KEY_ID": {
            "from": "secret",
            "name": "access_key_id"
          },
          "AWS_SECRET_ACCESS_KEY": {
            "from": "secret",
            "name": "secret_access_key"
          },
          "AWS_REGION": {
            "from": "value",
            "name": "region"
          },
          "AWS_DEFAULT_REGION": {
            "from": "value",
            "name": "region"
          },
          "AWS_ENDPOINT_URL_S3": {
            "from": "value",
            "name": "endpoint"
          }
        },
        "inputHints": {
          "AWS_ACCESS_KEY_ID": {
            "label": {
              "en": "Access key ID",
              "ja": "アクセスキー ID"
            },
            "required": true
          },
          "AWS_SECRET_ACCESS_KEY": {
            "label": {
              "en": "Secret access key",
              "ja": "シークレットアクセスキー"
            },
            "required": true
          },
          "AWS_REGION": {
            "label": {
              "en": "Region",
              "ja": "リージョン"
            },
            "placeholder": "auto",
            "required": false
          },
          "AWS_DEFAULT_REGION": {
            "hidden": true
          },
          "AWS_ENDPOINT_URL_S3": {
            "label": {
              "en": "S3 endpoint URL",
              "ja": "S3 endpoint URL"
            },
            "placeholder": "https://objects.example.com",
            "required": true
          }
        },
        "presentation": {
          "showInConnectionSetup": true,
          "displayName": {
            "en": "Static keys with endpoint",
            "ja": "静的キーと endpoint"
          },
          "description": {
            "en": "Use credentials and an endpoint issued by your S3-compatible service operator.",
            "ja": "利用する S3 互換サービスの運用者が発行した認証情報と endpoint を使います。"
          }
        }
      }
    }
  },
  {
    "id": "scaleway",
    "displayName": "Scaleway",
    "secretPartition": "provider-credentials",
    "terraformSource": [
      "scaleway/scaleway",
      "registry.opentofu.org/scaleway/scaleway"
    ],
    "envNames": [
      "SCW_ACCESS_KEY",
      "SCW_SECRET_KEY",
      "SCW_DEFAULT_PROJECT_ID",
      "SCW_DEFAULT_ORGANIZATION_ID",
      "SCW_DEFAULT_REGION",
      "SCW_DEFAULT_ZONE",
      "SCW_PROFILE"
    ],
    "requiredEnvGroups": [
      [
        "SCW_ACCESS_KEY",
        "SCW_SECRET_KEY"
      ],
      [
        "SCW_PROFILE"
      ]
    ],
    "authModes": {
      "access_key": {
        "env": {
          "SCW_ACCESS_KEY": {
            "from": "secret",
            "name": "access_key"
          },
          "SCW_SECRET_KEY": {
            "from": "secret",
            "name": "secret_key"
          },
          "SCW_DEFAULT_PROJECT_ID": {
            "from": "value",
            "name": "project_id"
          },
          "SCW_DEFAULT_ORGANIZATION_ID": {
            "from": "value",
            "name": "organization_id"
          },
          "SCW_DEFAULT_REGION": {
            "from": "value",
            "name": "region"
          },
          "SCW_DEFAULT_ZONE": {
            "from": "value",
            "name": "zone"
          }
        },
        "inputHints": {
          "SCW_ACCESS_KEY": {
            "label": {
              "en": "Access key",
              "ja": "アクセスキー"
            },
            "required": true
          },
          "SCW_SECRET_KEY": {
            "label": {
              "en": "Secret key",
              "ja": "シークレットキー"
            },
            "required": true
          },
          "SCW_DEFAULT_PROJECT_ID": {
            "label": {
              "en": "Project ID",
              "ja": "プロジェクト ID"
            },
            "required": false
          },
          "SCW_DEFAULT_ORGANIZATION_ID": {
            "label": {
              "en": "Organization ID",
              "ja": "組織 ID"
            },
            "required": false
          },
          "SCW_DEFAULT_REGION": {
            "label": {
              "en": "Region",
              "ja": "リージョン"
            },
            "required": false
          },
          "SCW_DEFAULT_ZONE": {
            "label": {
              "en": "Zone",
              "ja": "ゾーン"
            },
            "required": false
          }
        },
        "presentation": {
          "showInConnectionSetup": true,
          "displayName": {
            "en": "Access key",
            "ja": "アクセスキー"
          }
        }
      },
      "profile": {
        "env": {
          "SCW_PROFILE": {
            "from": "value",
            "name": "profile"
          }
        }
      }
    }
  },
  {
    "id": "vercel",
    "displayName": "Vercel",
    "secretPartition": "provider-credentials",
    "terraformSource": [
      "vercel/vercel",
      "registry.opentofu.org/vercel/vercel"
    ],
    "envNames": [
      "VERCEL_API_TOKEN"
    ],
    "requiredEnvGroups": [
      [
        "VERCEL_API_TOKEN"
      ]
    ],
    "authModes": {
      "api_token": {
        "env": {
          "VERCEL_API_TOKEN": {
            "from": "secret",
            "name": "api_token"
          }
        },
        "inputHints": {
          "VERCEL_API_TOKEN": {
            "label": {
              "en": "API token",
              "ja": "API トークン"
            },
            "required": true
          }
        },
        "presentation": {
          "showInConnectionSetup": true,
          "displayName": {
            "en": "API token",
            "ja": "API トークン"
          }
        }
      }
    }
  },
  {
    "id": "vultr",
    "displayName": "Vultr",
    "secretPartition": "provider-credentials",
    "terraformSource": [
      "vultr/vultr",
      "registry.opentofu.org/vultr/vultr"
    ],
    "envNames": [
      "VULTR_API_KEY"
    ],
    "requiredEnvGroups": [
      [
        "VULTR_API_KEY"
      ]
    ],
    "authModes": {
      "api_key": {
        "env": {
          "VULTR_API_KEY": {
            "from": "secret",
            "name": "api_key"
          }
        },
        "inputHints": {
          "VULTR_API_KEY": {
            "label": {
              "en": "API key",
              "ja": "API キー"
            },
            "required": true
          }
        },
        "presentation": {
          "showInConnectionSetup": true,
          "displayName": {
            "en": "API key",
            "ja": "API キー"
          }
        }
      }
    }
  }
];
