import { readFile, writeFile } from "node:fs/promises";
import { join } from "node:path";
import Ajv2020 from "ajv/dist/2020.js";
import standaloneCode from "ajv/dist/standalone/index.js";

const root = join(new URL("..", import.meta.url).pathname);
const outputPath = join(
  root,
  "core/shared/json-schema/draft_2020_schema.generated.ts",
);

const ajv = new Ajv2020({
  allErrors: true,
  strict: false,
  validateFormats: false,
  code: { esm: true, lines: true, source: true },
});
const generated = finalize(
  standaloneCode(ajv, {
    validateDraft202012Schema: "https://json-schema.org/draft/2020-12/schema",
  }),
);

if (process.argv.includes("--check")) {
  const current = await readFile(outputPath, "utf8").catch(() => "");
  if (current !== generated) {
    throw new Error(
      "core/shared/json-schema/draft_2020_schema.generated.ts is stale; run bun run schema-validators:assets",
    );
  }
} else {
  await writeFile(outputPath, generated);
}

function finalize(source: string): string {
  const output = source
    .replace(
      'const func1 = require("ajv/dist/runtime/ucs2length").default;\n',
      'import { ucs2length as func1 } from "@cfworker/json-schema";\n',
    )
    .replace(
      'const func0 = require("ajv/dist/runtime/equal").default;\n',
      'import { deepCompareStrict as func0 } from "@cfworker/json-schema";\n',
    );
  if (
    /\brequire\s*\(|\beval\s*\(|\bnew\s+Function\b|from\s+["']ajv\//u.test(
      output,
    )
  ) {
    throw new Error(
      "generated validators contain an Ajv runtime dependency or runtime code generation",
    );
  }
  return (
    "// Generated by scripts/build-schema-validators.ts. Do not edit.\n" +
    "// @ts-nocheck -- Ajv standalone emits optimized JavaScript.\n" +
    output
  );
}
