import { readFile, writeFile } from "node:fs/promises";
import { dirname, join, relative } from "node:path";
import { fileURLToPath } from "node:url";
import Ajv2020 from "ajv/dist/2020.js";
import standaloneCode from "ajv/dist/standalone/index.js";
import formDefinitionSchema from "../core/adapters/takoform/schemas/form-definition.schema.json" with { type: "json" };
import formRefSchema from "../core/adapters/takoform/schemas/form-ref.schema.json" with { type: "json" };
import packageIndexSchema from "../core/adapters/takoform/schemas/package-index.schema.json" with { type: "json" };

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const takoformOutputPath = join(
  root,
  "core/adapters/takoform/schema_validators.generated.ts",
);
const draftOutputPath = join(
  root,
  "core/shared/json-schema/draft_2020_schema.generated.ts",
);

function createAjv(): Ajv2020 {
  return new Ajv2020({
    allErrors: true,
    strict: false,
    validateFormats: false,
    code: { esm: true, lines: true, source: true },
  });
}

const ajv = createAjv();
ajv.addSchema(formRefSchema);
ajv.addSchema(packageIndexSchema);
ajv.addSchema(formDefinitionSchema);

const takoformGenerated = finalize(
  standaloneCode(ajv, {
    validateFormRef: formRefSchema.$id,
    validatePackageIndex: packageIndexSchema.$id,
    validateFormDefinition: formDefinitionSchema.$id,
  }),
);

const draftAjv = createAjv();
const draftGenerated = finalize(
  standaloneCode(draftAjv, {
    validateDraft202012Schema: "https://json-schema.org/draft/2020-12/schema",
  }),
);

// Ajv's standalone generator emits CommonJS requires for two tiny runtime
// helpers. Point them at the already-required eval-free Workers interpreter
// package so release builds do not need Ajv (a build-time dependency).
function finalize(generated: string): string {
  const output = generated
    .replace(
      'const func1 = require("ajv/dist/runtime/ucs2length").default;\n',
      'import { ucs2length as func1 } from "@cfworker/json-schema";\n',
    )
    .replace(
      'const func0 = require("ajv/dist/runtime/equal").default;\n',
      'import { deepCompareStrict as func0 } from "@cfworker/json-schema";\n',
    );
  if (
    /\brequire\s*\(|\beval\s*\(|\bnew\s+Function\b|from\s+["']ajv\//u.test(
      output,
    )
  ) {
    throw new Error(
      "generated validators contain an Ajv runtime dependency or runtime code generation",
    );
  }
  return (
    "// Generated by scripts/build-takoform-schema-validators.ts. Do not edit.\n" +
    "// @ts-nocheck -- Ajv standalone emits optimized JavaScript.\n" +
    output
  );
}

if (process.argv.includes("--check")) {
  const currentTakoform = await readFile(takoformOutputPath, "utf8").catch(
    () => "",
  );
  const currentDraft = await readFile(draftOutputPath, "utf8").catch(() => "");
  if (
    currentTakoform !== takoformGenerated ||
    currentDraft !== draftGenerated
  ) {
    throw new Error(
      `${relative(root, takoformOutputPath)} or ${relative(root, draftOutputPath)} is stale; run bun run takoform-schema-validators:assets`,
    );
  }
} else {
  await writeFile(takoformOutputPath, takoformGenerated);
  await writeFile(draftOutputPath, draftGenerated);
}
