/**
 * Mock install_preview service for local-substrate.
 *
 * Primary path: load pre-baked fixtures from /srv/fixtures/<repo>.json
 * (generated by scripts/refresh-preview-fixtures.sh from each bundled
 * app's real `.takosumi/app.yml`). This gives the install wizard real
 * bindings + grants + appId so the downstream materialize / OIDC client
 * registration / etc. paths are actually exercised.
 *
 * Fallback path: if no fixture matches the repo, derive deterministic
 * fake values from sha256(gitUrl+ref) so smoke tests against arbitrary
 * URLs don't break — but log a warning so the operator knows the wizard
 * is running blind.
 *
 * Wire env (worker → mock):
 *   TAKOSUMI_ACCOUNTS_INSTALL_PREVIEW_URL=http://install-preview-mock:8788
 */

const PORT = Number(Deno.env.get('PORT') ?? '8788');

async function sha256Hex(input: string): Promise<string> {
  const buf = await crypto.subtle.digest('SHA-256', new TextEncoder().encode(input));
  return [...new Uint8Array(buf)].map((b) => b.toString(16).padStart(2, '0')).join('');
}

function appIdFromGitUrl(gitUrl: string): string {
  try {
    const u = new URL(gitUrl);
    const last = u.pathname.split('/').filter(Boolean).pop() ?? 'fake-app';
    return last.replace(/\.git$/, '');
  } catch {
    return 'fake-app';
  }
}

const FIXTURE_DIR = '/srv/fixtures';

async function loadFixture(repoBasename: string): Promise<Record<string, unknown> | null> {
  try {
    const text = await Deno.readTextFile(`${FIXTURE_DIR}/${repoBasename}.json`);
    return JSON.parse(text);
  } catch {
    return null;
  }
}

Deno.serve({ port: PORT, hostname: '0.0.0.0' }, async (req) => {
  const url = new URL(req.url);
  if (url.pathname === '/healthz') {
    return new Response('ok', { headers: { 'content-type': 'text/plain' } });
  }
  if (url.pathname !== '/v1/install/preview') {
    return Response.json({ error: 'not_found' }, { status: 404 });
  }
  if (req.method !== 'POST') {
    return Response.json({ error: 'method_not_allowed' }, { status: 405 });
  }

  let body: Record<string, unknown> = {};
  try {
    body = await req.json();
  } catch {
    return Response.json({ error: 'invalid_json' }, { status: 400 });
  }

  const source = (body.source ?? {}) as Record<string, unknown>;
  const gitUrl = String(source.gitUrl ?? source.url ?? body.gitUrl ?? '');
  const ref = String(source.ref ?? body.ref ?? 'main');
  if (!gitUrl) {
    return Response.json({ error: 'invalid_request', error_description: 'source.gitUrl required' }, { status: 400 });
  }

  const repoBasename = appIdFromGitUrl(gitUrl);

  // Fixture path: real .takosumi/app.yml-derived response if we have one.
  const fixture = await loadFixture(repoBasename);
  if (fixture) {
    // Override ref + (re-derive commit only when caller asked for a
    // different ref) so the wizard's ref-input still drives variation.
    const src = (fixture.source ?? {}) as Record<string, unknown>;
    if (ref !== src.ref) {
      const fp = await sha256Hex(`${gitUrl}@${ref}`);
      fixture.source = {
        ...src,
        ref,
        commit: fp.slice(0, 40),
        appManifestDigest: `sha256:${fp}`,
        compiledManifestDigest: `sha256:${fp}`,
      };
    }
    console.log(
      `[install-preview-mock] fixture-hit ${repoBasename} → appId=${fixture.appId} ` +
        `bindings=${((fixture.bindings ?? []) as unknown[]).length} ` +
        `grants=${((fixture.grants ?? []) as unknown[]).length}`,
    );
    return Response.json(fixture);
  }

  // Fallback: deterministic fake (preserves backwards compat for arbitrary
  // git URLs). Loud-warn so operator knows the wizard is running blind.
  const fingerprint = await sha256Hex(`${gitUrl}@${ref}`);
  const commit = fingerprint.slice(0, 40);
  const digest = fingerprint;
  console.warn(
    `[install-preview-mock] FALLBACK no fixture for ${repoBasename}; ` +
      `returning empty bindings/grants. Run scripts/refresh-preview-fixtures.sh ` +
      `to add this repo to the fixture set.`,
  );

  return Response.json({
    appId: repoBasename,
    source: {
      gitUrl,
      ref,
      commit,
      appManifestDigest: `sha256:${digest}`,
      compiledManifestDigest: `sha256:${digest}`,
    },
    bindings: [],
    grants: [],
    metadata: {
      mock: true,
      fixture: false,
      service: 'install-preview-mock (local-substrate)',
      generatedAt: new Date().toISOString(),
    },
  });
});

console.log(`[install-preview-mock] listening on :${PORT}`);
