/**
 * Unit test for the COSE/CBOR helpers used by the passkey register flow.
 *
 * Fixtures live in __fixtures__/attestation-objects.json and were
 * generated by a Python script that builds WebAuthn-shaped attestation
 * objects from real P-256 / P-384 / P-521 / RSA2048 keypairs. The test
 * decodes each fixture and asserts the resulting JWK is byte-identical to
 * the public key the generator produced. If the SPA's CBOR decoder or
 * COSE→JWK converter regresses, this catches it without depending on a
 * browser / hardware authenticator.
 *
 * Regenerate fixtures (the generator is colocated in __fixtures__/):
 *   cd src/lib/webauthn/__fixtures__
 *   python3 generate.py > attestation-objects.json
 */
import { describe, expect, it } from "vitest";
import { b64urlToBuf, coseToJwk, extractCosePublicKey } from "./cose";
import fixtures from "./__fixtures__/attestation-objects.json" with {
  type: "json",
};

interface Fixture {
  attestationObjectB64url: string;
  expectedCredentialIdB64url: string;
  expectedJwk: JsonWebKey;
}

const CASES: ReadonlyArray<[string, Fixture]> = Object.entries(
  fixtures as Record<string, Fixture>,
);

describe("extractCosePublicKey + coseToJwk", () => {
  for (const [label, fx] of CASES) {
    it(`recovers ${label} public key as JWK`, () => {
      const attObj = b64urlToBuf(fx.attestationObjectB64url);
      const cose = extractCosePublicKey(attObj);
      const jwk = coseToJwk(cose);
      expect(jwk).toEqual(fx.expectedJwk);
    });
  }
});
